### ISSUE TITLE
ServiceCollectionServicesExtensions why?

### ISSUE THREAD

**Issue by joslat** [ChilliCream/graphql-workshop#10]
I think it would look more ellegant to register the service for the token store in the Startup, now Program.cs.. 

"return services.AddSingleton<ITokenStore, TokenStore>();" which is where all the other registrations of services are..
Otherwise we have a mystical line "builder.Services.AddServices();" which is a bit unclear..

What do you think?

**Comment by michaelstaib** [comment]
It is actually best practice to wrap service registrations into extension functions. But AddServices is not a great name... maybe we should be more explicit with AddTokenStore().AddThis().AddThat()

**Comment by joslat** [comment]
agree. closed as we renamed it as suggested :).
