### ISSUE TITLE
url not found in workshop

### ISSUE THREAD

**Issue by JannemanDev** [ChilliCream/graphql-workshop#103]
In this section:  
https://github.com/ChilliCream/graphql-workshop/blob/master/docs/1-creating-a-graphql-server-project.md#adding-mutations  

Relay mutation pattern link gives 404 Not Found:  
[relay mutation pattern](https://relay.dev/docs/en/graphql-server-specification.html#mutations)

**Comment by glen-84** [comment]
I'm closing this issue as outdated, as we have an updated workshop on the `main` branch, for Hot Chocolate 14.
