### ISSUE TITLE
[ScopedService] is Obsolete, but using [Service(ServiceKind.Pooled)] fails

### ISSUE THREAD

**Issue by pankaj-kansodariya** [ChilliCream/graphql-workshop#106]
As per [GraphQL-Workshop](https://github.com/ChilliCream/graphql-workshop) and [Session #3 Understanding GraphQL query execution and DataLoader](https://github.com/ChilliCream/graphql-workshop/blob/master/docs/3-understanding-dataLoader.md)

I followed Steps 3, 4, 5, 6 & 7 and everything worked as expected.
But Warning is shown while using [ScopedService] that it is **Obsolete** and I should use **[Service(ServiceKind.Pooled)] or [Service(ServiceKind.Resolver)]**.
But when I use either [Service(ServiceKind.Pooled)] or [Service(ServiceKind.Resolver)] then getting error as following.

"**No service for type 'Microsoft.Extensions.ObjectPool.ObjectPool`1[ApplicationDbContext]' has been registered.**"

**Comment by PascalSenn** [comment]
If you still want use the pooled db context with 13, the easiest thing to do is to register the db context on the schema as pooled. `RegisterDbContext<FooContext>(Pooled)`. You then do not need any attribute

**Comment by pankaj-kansodariya** [comment]
So if we consider to solve the issue of Parallel execution of DbContext, we have following multiple options

Option 1:
If DbContext is registered as Services.AddDbContext() then need to use [Service(ServiceKind.Synchronized)]

Option: 2
If DbContext is registered as Services.AddDbContext() then need to use IRequestExecutorBuilder.RegisterDbContext(DbContextKind.Synchronized) and no need specify [Service] attribute.

Option: 3
If DbContext is registered as Services.AddPooledDbContextFactory() then need to use IRequestExecutorBuilder.RegisterDbContext(DbContextKind.Pooled) and no need specify [Service] attribute.

in that case, which scenario is suitable for using ObjectFieldDescriptorExtensions and UseApplicationDbContextAttribute ?

**Comment by PascalSenn** [comment]
@pankaj-kansodariya  You do not need the UseApplicationDbContextAttribute anymore when you do option 3 

If you do not have a pooled db context then you can also just use the DbContextKind.Resolver where we open a DI scope per resolver. But if you already have it set up to use the Pooled version of it, just go for DbContextKind.Pooled and do not worry about UseDbContext and [Service]

**Comment by jeffvan98** [comment]
It would be helpful to get an updated set of instructions for Session #3, just like @pankaj-kansodariya mentioned.

**Comment by weirdyang** [comment]
I am trying to resolve this using option 3, but there doesn't seem to be  `RegisterDbContext` ?

![image](https://github.com/ChilliCream/graphql-workshop/assets/25576022/6f6dbc3c-3ca5-4473-ba43-97c5fb1cf9df)

using "HotChocolate.AspNetCore" Version="13.5.1" 

solution: Add package HotChocolate.Data.EntityFramework

**Comment by thistlehouse** [comment]
> I am trying to resolve this using option 3, but there doesn't seem to be `RegisterDbContext` ?
> 
> ![image](https://private-user-images.githubusercontent.com/25576022/277114517-6f6dbc3c-3ca5-4473-ba43-97c5fb1cf9df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NzA2NzAsIm5iZiI6MTcxMjg3MDM3MCwicGF0aCI6Ii8yNTU3NjAyMi8yNzcxMTQ1MTctNmY2ZGJjM2MtM2NhNS00NDczLWJhNDMtOTdjNWZiMWNmOWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDIxMTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZDM0YmQ0MmJkZjg4NmYzMjFkZDhhMjdlY2QxMGFjOTQxZWM0NTQ0MWI5ZGQyMGI2Y2ExZmZhZGU2YzY3MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9JAl2KSxiKthhrdNj4BkXh1-zGv3eagEp4d1F-_zFw8)
> 
> using "HotChocolate.AspNetCore" Version="13.5.1"
> 
> solution: Add package HotChocolate.Data.EntityFramework

dotnet add package HotChocolate.Data.EntityFramework

**Comment by thistlehouse** [comment]
> I am trying to resolve this using option 3, but there doesn't seem to be `RegisterDbContext` ?
> 
> ![image](https://private-user-images.githubusercontent.com/25576022/277114517-6f6dbc3c-3ca5-4473-ba43-97c5fb1cf9df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NzA2NzAsIm5iZiI6MTcxMjg3MDM3MCwicGF0aCI6Ii8yNTU3NjAyMi8yNzcxMTQ1MTctNmY2ZGJjM2MtM2NhNS00NDczLWJhNDMtOTdjNWZiMWNmOWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDIxMTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZDM0YmQ0MmJkZjg4NmYzMjFkZDhhMjdlY2QxMGFjOTQxZWM0NTQ0MWI5ZGQyMGI2Y2ExZmZhZGU2YzY3MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9JAl2KSxiKthhrdNj4BkXh1-zGv3eagEp4d1F-_zFw8)
> 
> using "HotChocolate.AspNetCore" Version="13.5.1"
> 
> solution: Add package HotChocolate.Data.EntityFramework

With HotChocolate.Data.EntityFramework, I don't need to add .UseDbContext<ApplicationDbContext>() to the descriptor?

**Comment by glen-84** [comment]
I'm closing this issue as outdated, as we have an updated workshop on the `main` branch, for Hot Chocolate 14.
