### ISSUE TITLE
Caching is not working - Not returning any data on query - on version 13.9.1

### ISSUE THREAD

**Issue by baytekink** [ChilliCream/graphql-workshop#111]
Caching is not working, actually not returning any data from query, but if I close .UseQueryCachePipeline() I can see the data when queriying.

It adds the Cache Control header but not returning any value

I published the code to public github: https://github.com/baytekink/GraphQL you can download and start directly to test

**Comment by glen-84** [comment]
If you're still experiencing this issue, then please open an issue in the [GraphQL Platform](https://github.com/ChilliCream/graphql-platform) repository.
