### ISSUE TITLE
Dev can't follow Session 6 as it requires missing mutatutions

### ISSUE THREAD

**Issue by ztolley** [ChilliCream/graphql-workshop#15]
In Session 6 it talks about adding pagination and demonstrates that with a query for tracks to include paginated sessions.

Unfortunately at that point int he workshop there is no way to add a track and associate or schedule sessions to it.

I think the mutation comes later on but without it the dev gets an error. Also would it be possible to include some example queries to cut and paste to help populate the DB to be able to follow the workshop?

**Comment by whengely** [comment]
I ran into this same issue.

**Comment by michaelstaib** [comment]
- [ ] Add example mutations to populate the database
- [ ]  Fix inconsistency with tracks

**Comment by gojanpaolo** [comment]
@michaelstaib I think we can opt for a seeding the database and just briefly mention it within the workshop. That way, all query samples would work without any manual mutation/setup.

**Comment by mdit** [comment]
I'm struggling with this issue too and it's making continuing the rest of the workshop pretty difficult. 
It would be very useful if the GraphQL syntax to add sessions and tracks was available - I think this is more useful for newbies like myself than seeding the db using EF.  I'm struggling particularly to know the syntax for providing the speakerIds to the addSession mutation.

**Comment by glen-84** [comment]
I'm closing this issue as outdated, as we have an updated workshop on the `main` branch, for Hot Chocolate 14.
