### ISSUE TITLE
Breaking changes Schema Explorer using 11.0.0-rc.0

### ISSUE THREAD

**Issue by Timo-DK** [ChilliCream/graphql-workshop#16]
I am following the workshop and I see that since the introduction of recommending to use `HotChocolate.AspNetCore 11.0.0-rc.0` it introduced breaking changes for the Schema Explorer in Banana Cake Pop.

At first I believed I did something wrong, but I went on and downloaded the source code of this repository to check if the completed session 1 code is also breaking, and it is. I went through the commits of this repository to find the session 1 with the "old" API of version 10.5.X. and that worked.

I am not sure what the problems is, but I know that it is breaking here:
![image](https://user-images.githubusercontent.com/6235760/98467756-5bfe2680-21d7-11eb-9553-6ea278850022.png)

The "old" API uses the following syntax that works:
![image](https://user-images.githubusercontent.com/6235760/98467783-6fa98d00-21d7-11eb-904e-25972455aab4.png)

**Comment by michaelstaib** [comment]
Yes 11 has breaking changes regarding the config api. With 11 we have a new unified config api.
