### ISSUE TITLE
Schema endpoint does not seem to work

### ISSUE THREAD

**Issue by Julien-Sytadelle** [ChilliCream/graphql-workshop#18]
Hi,

I cannot figure how to get the schema as graphql or json with 11.0.0.rc2 or rc4.
Neither http://localhost:5000/schema or http://localhost:5000/graphql/schema works.
I read a lot of threads in slack but in vain.

Could you add a section explaining this point ?  
For now, I use npm package get-graphql-schema to provide it to my client. 

Best,

**Comment by michaelstaib** [comment]
http://localhost:5000/graphql?sdl

**Comment by Julien-Sytadelle** [comment]
Thanks a lot !

**Comment by michaelstaib** [comment]
we will add this to the migration docs.
