### ISSUE TITLE
Should the latter GetAttendeeAsync in SessionAttendeeCheckIn be GetSessionAsync instead?

### ISSUE THREAD

**Issue by gojanpaolo** [ChilliCream/graphql-workshop#29]
The class `SessionAttendeeCheckIn` currently have two definitions of `GetAttendeeAsync`

https://github.com/ChilliCream/graphql-workshop/blob/2e8171135be0be21d49f1c5621744639bc72e066/code/complete/GraphQL/Attendees/SessionAttendeeCheckIn.cs#L35-L43

But it seems to me that the latter should be `GetSessionAsync` instead. Or am I missing something?

That part is specifically covered in 7-subscriptions.
... # 2 in https://github.com/ChilliCream/graphql-workshop/blob/master/docs/7-subscriptions.md#add-onattendeecheckedin-subscription

I'll be happy to create a PR if it needs correction

Btw, thank you for creating this workshop. I'm learning graphql and I'm having a great learning experience so far.

**Comment by michaelstaib** [comment]
Yeas that is correct ....  do you want to do a pull-request for this?

**Comment by gojanpaolo** [comment]
@michaelstaib sure 👍
