### ISSUE TITLE
Add typing indicator

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/graphql-workshop#3]

**Comment by joslat** [comment]
added a timer implementation in the Main.razor, we set the datetime whenever we get this event and we keep checking at 5 second intervals with a timer. if the timer's datetime is greater than 10 seconds, we set the istyping to false.

Nowadays, I cannot find in local or in git how this mutation is notified to the server..

**Comment by joslat** [comment]
I believe I need you here for this, as I do not see this is happening, nobody raises the event to the server and the client cannot get it. Maybe I am wrong but would be happy to be..

**Comment by michaelstaib** [comment]
This one is now working.
