### ISSUE TITLE
AddTypeExtension vs AddType

### ISSUE THREAD

**Issue by gojanpaolo** [ChilliCream/graphql-workshop#31]
In [4-schema-design](https://github.com/ChilliCream/graphql-workshop/blob/master/docs/4-schema-design.md), `AddTypeExtension` and `AddType` is used interchangeably. I'm curious as well as confused because of this. I'll probably be able to clarify this later when I get to learn more about graphql and hc. But any response will be greatly appreciated.

e.g.

> 14. Head back to the `Startup.cs` and add the `TrackMutations` to the schema builder.
>
>   ```csharp
>     services
>         .AddGraphQLServer()
>         .AddQueryType(d => d.Name("Query"))
>             .AddTypeExtension<SpeakerQueries>()
>         .AddMutationType(d => d.Name("Mutation"))
>             .AddTypeExtension<SessionMutations>()
>             .AddTypeExtension<SpeakerMutations>()
>             .AddTypeExtension<TrackMutations>()
>         .AddType<AttendeeType>()
>         .AddType<SessionType>()
>         .AddType<SpeakerType>()
>         .AddType<TrackType>()
>         .EnableRelaySupport()
>         .AddDataLoader<SpeakerByIdDataLoader>()
>         .AddDataLoader<SessionByIdDataLoader>();
>    ```

---

> 6. Again, head over to the `Startup.cs` and register the `TrackQueries` with the schema builder.
> 
>    ```csharp
>    services
>         .AddGraphQLServer()
>         .AddQueryType(d => d.Name("Query"))
>             .AddType<SessionQueries>()
>             .AddType<SpeakerQueries>()
>             .AddType<TrackQueries>()
>         .AddMutationType(d => d.Name("Mutation"))
>             .AddType<SessionMutations>()
>             .AddType<SpeakerMutations>()
>             .AddType<TrackMutations>()
>         .AddType<AttendeeType>()
>         .AddType<SessionType>()
>         .AddType<SpeakerType>()
>         .AddType<TrackType>()
>         .EnableRelaySupport();
>    ```

**Comment by michaelstaib** [comment]
So, they actually can be used both ... we are however diverting to use `AddTypeExtension` to be more semantically correct. There might still be old code examples in the workshop that use AddType instead of `AddTypeExtension`. 

Do you want to do a pull-request?

**Comment by gojanpaolo** [comment]
@michaelstaib sure 👍

**Comment by michaelstaib** [comment]
Awesome! Thanks for your help on this!
