### ISSUE TITLE
Add EF .config folder to .gitignore -  dotnet-tools.json  problem based on location zone..

### ISSUE THREAD

**Issue by damikun** [ChilliCream/graphql-workshop#38]
**Problem:**
In some machines you can have problem to use ef because of dotnet-tools.json was created on different machine.. And is included in project... Windows use location timestamp

**Location:**
https://github.com/ChilliCream/graphql-workshop/tree/master/code/complete/.config   (and all others)

**Error**
```
File  ..../graphql-workshop-master\graphql-workshop-master\code\complete\.config\dotnet-tools.json came from another computer and might be blocked to help protect this computer. For more information, including how to unblock, see https://aka.ms/motw
```

![image](https://user-images.githubusercontent.com/54806834/104290850-21f11f80-54bb-11eb-9f7a-98d68393267e.png)

Removing of course solve the problem..

**Recommendation**
Moving all this .config folders to .gitignore  (not needed to update database)... If needed and people follow workshop tools will be installed from it...

**Comment by glen-84** [comment]
I'm closing this issue as outdated, as we have an updated workshop on the `main` branch, for Hot Chocolate 14.
