### ISSUE TITLE
Is `NonNullType` still necessary when nullable reference types is enabled?

### ISSUE THREAD

**Issue by gojanpaolo** [ChilliCream/graphql-workshop#42]
[Session # 2](https://github.com/ChilliCream/graphql-workshop/blob/master/docs/2-controlling-nullability.md) demonstrates how HC leverages C#'s nullable reference types.
In [Session # 6](https://github.com/ChilliCream/graphql-workshop/blob/master/docs/6-adding-complex-filter-capabilities.md) `NonNullType` is used...

```
.ResolveWith<TrackResolvers>(t => t.GetSessionsAsync(default!, default!, default))
.UsePaging<NonNullType<SessionType>>()
```

...but it looks like it doesn't affect the generated schema at all.

The graphql type nullability is controlled by nullable reference types:
- `Task<IEnumerable<Session>> GetSessionsAsync` for non-nullable `Session`
- `Task<IEnumerable<Session?>> GetSessionsAsync` for nullable `Sessions`

Is it ok to remove the use of `NonNullType` if nullable reference types is enabled?

**Comment by glen-84** [comment]
I'm closing this issue as outdated, as we have an updated workshop on the `main` branch, for Hot Chocolate 14.
