### ISSUE TITLE
Can't complete workshop

### ISSUE THREAD

**Issue by LeandroRezendeCoutinho** [ChilliCream/graphql-workshop#44]
Hello guys...
I have completed the session 1. 
Accessing http://localhost:5000/graphql/ in browser always get this...
![image](https://user-images.githubusercontent.com/12284806/105644163-b6bc2b80-5e72-11eb-8757-e116e5aff71a.png)

**Comment by LeandroRezendeCoutinho** [comment]
Need just to reload schema. It is not in docs. Maybe it should...
![image](https://user-images.githubusercontent.com/12284806/105644281-a48ebd00-5e73-11eb-9984-0f567e201f93.png)

**Comment by michaelstaib** [comment]
It’s a bug in bcp. Will be fixed soon.
