### ISSUE TITLE
Error at Session #3: GraphQL schema design approaches 

### ISSUE THREAD

**Issue by jankvapil** [ChilliCream/graphql-workshop#5]
Hello, I'm trying to complete the third part of this tutorial and I can't get past the definition of more types. Everything works well till the "Enable Relay support" section. But when I try to add more data loaders and schema types, my program crashes with this error message:

"An unhandled exception of type 'HotChocolate.SchemaException' occurred in System.Private.CoreLib.dll
The name `Mutation` was already registered by another type. - Type: Mutation"

I tried to rewrite it twice, to find the source of the error, but I didn't come up with anything. I would be grateful if there was someone who could look at it. [Here is my project repository](https://github.com/jkvapil6/ConferencePlanner).

**Comment by otryshko** [comment]
@jkvapil6 in Startup.cs, it should be AddQueryType(d => d.Name("**Query**")), not Mutation (at the moment, both AddQueryType and AddMutationType use "Mutation"
CC: @michaelstaib

**Comment by michaelstaib** [comment]
@otryshko is right, that is the issue.
