### ISSUE TITLE
Session 3 - missing explanation (reference) of using ToListAsync instead of IQueryable

### ISSUE THREAD

**Issue by Arsync** [ChilliCream/graphql-workshop#56]
In Session 3 found
> Important: Note, that we no longer are returning the IQueryable but are executing the IQueryable by using ToListAsync. We will explain why later in the middleware and filter session.

But where to find it explanation? In Session 5 something about middleware, but in 6-th there is... IQueryable, again! How this magic works?
```cs
[UseApplicationDbContext]
[UsePaging]
public IQueryable<Track> GetTracks(
    [ScopedService] ApplicationDbContext context) =>
    context.Tracks.OrderBy(t => t.Name);
```
I've tried in my project:
```cs
[UsePersonDbContext]
[UseProjection]
public IQueryable<EducactionLevel> GetEducactionLevels(
    [ScopedService] PersonDbContext context)
{
    return context.EducactionLevels;
}
```
where PersonDbContext is registered by `services.AddPooledDbContextFactory<PersonDbContext>(...)`, but got

> Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
> Object name: 'PersonDbContext'.

So question is:
- How to use projections with PooledDbContextFactory?

**Comment by Arsync** [comment]
If I replace all of this
```cs
    public static class ObjectFieldDescriptorExtensions
    {
        public static IObjectFieldDescriptor UseDbContext<TDbContext>(
            this IObjectFieldDescriptor descriptor)
            where TDbContext : DbContext
        {
            return descriptor.UseScopedService(
                create: s => s.GetRequiredService<IDbContextFactory<TDbContext>>().CreateDbContext(),
                disposeAsync: (_, c) => c.DisposeAsync());
        }
    }
```
```cs
    public class UsePersonDbContextAttribute : ObjectFieldDescriptorAttribute
    {
        public override void OnConfigure(
            IDescriptorContext context,
            IObjectFieldDescriptor descriptor,
            MemberInfo member)
        {
            descriptor.UseDbContext<PersonDbContext>();
        }
    }
```
Just with one line:
```cs
[UseDbContext(typeof(PersonDbContext))] // <-- there it is
[UseProjection]
public IQueryable<EducactionLevel> GetEducactionLevels(
    [ScopedService] PersonDbContext context)
{
    return context.EducactionLevels;
}
```
It start working! As described in EntityFramework [article](https://chillicream.com/docs/hotchocolate/integrations/entity-framework). Why it different from 11_1 graphql-workshop?

Even better to do attribute like
```cs
public class UsePersonDbContextAttribute : UseDbContextAttribute
{
    public UsePersonDbContextAttribute()
        : base(typeof(PersonDbContext))
    {

    }
}
```

**Comment by Abdullah-onGit** [comment]
What about ToListAsync to IQueryable? 
Any idea

**Comment by michaelstaib** [comment]
@Arsync I has no time to update this workshop. Some things are now much easier.

**Comment by michaelstaib** [comment]
@Abdullah-onGit think of `IQueryable` as a query builder. By returning `IQueryable` other middleware is able to rewrite the query.
