### ISSUE TITLE
Doc correction in 3-understanding-dataLoader.md

### ISSUE THREAD

**Issue by InvalidMethod** [ChilliCream/graphql-workshop#6]
3-understanding-dataLoader.md, section Fluent type configurations, Step 4. - Description says to add SessionType class.  Code example shows SpeakerType instead.  I think SessionType should be SpeakerType.  Step 7. Query should be for speakers instead of speaker since no id is provided

**Comment by michaelstaib** [comment]
Thanks for reporting. It is now fixed.
