### ISSUE TITLE
Session 3: UseApplicationDbContextAttribute not necessary?

### ISSUE THREAD

**Issue by MisterGoodcat** [ChilliCream/graphql-workshop#79]
I'm trying to understand why creating a separate `UseApplicationDbContextAttribute` (and the `IObjectFieldDescriptor` extension) would be necessary at all (steps 5+6 and usage later). I've been loosely following the examples and could not force/reproduce the parallel execution error. Digging into the sources, I found that the default [UseDbContext attribute](https://github.com/ChilliCream/hotchocolate/blob/ee5813646fdfea81035c681989793514f33b5d94/src/HotChocolate/Data/src/EntityFramework/UseDbContextAttribute.cs) that's coming with the EntityFramework package forwards to [a built-in extension method for IObjectFieldDescriptor](https://github.com/ChilliCream/hotchocolate/blob/ee5813646fdfea81035c681989793514f33b5d94/src/HotChocolate/Data/src/EntityFramework/Extensions/EntityFrameworkObjectFieldDescriptorExtensions.cs#L18) that's basically already doing the same thing like the manually implemented logic in session 3, doesn't it?

Am I correct that this separate implementation on the application level is not necessary anymore?

**Comment by MisterGoodcat** [comment]
Any update on this?

One use case I found for using a custom attribute is when you want to dynamically configure something on the DbContext after creation that cannot be achieved in the global configure hook. For example, if you want to dynamically change the connection string/database user based on the situation, this approach provides a good hook to do that. 

Otherwise my above judgement stands, what is described in the workshop does not seem to be required for any default scenario, and could be skipped safely.

**Comment by michaelstaib** [comment]
We are revamping the workshop at the moment for version 12.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/graphql-workshop/tree/master/code/complete/GraphQL

looked at this complete example... its the current draft for the new workshop.

**Comment by michaelstaib** [comment]
We are still working on it .... so its not final yet :)

**Comment by glen-84** [comment]
I'm closing this issue as outdated, as we have an updated workshop on the `main` branch, for Hot Chocolate 14.
