### ISSUE TITLE
Data Annotations

### ISSUE THREAD

**Issue by jankvapil** [ChilliCream/graphql-workshop#8]
Hi. I noticed that data annotations like `[StringLength(100)]` or `[MinLength(10), MaxLength(20)]` have no effect on generated database. For example Data/Speaker class from Session 6 looks in SQL like this: 

```
CREATE TABLE "Speakers" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Speakers" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "Bio" TEXT NULL,
    "WebSite" TEXT NULL)
```
Is this correct behaviour?

**Comment by michaelstaib** [comment]
This is part of EF so we just copied them over from the original ASP.NET core example. It might be that SQL Lite does not interpret them.

**Comment by jankvapil** [comment]
Thanks for answer. I tested it on MSSql insted of SQLite and now it works.
