### ISSUE TITLE
There was no argument with the name `speaker` found on the field `sessions

### ISSUE THREAD

**Issue by rjax** [ChilliCream/graphql-workshop#82]
version 12.0.1
In the Fluent Type configuration section, step 4 of 3-understanding-dataloader.md, the code 

```C#
   private class SpeakerResolvers
        {
            public async Task<IEnumerable<Session>> GetSessionsAsync(
                Speaker speaker,
                [ScopedService] ApplicationDbContext dbContext,
                SessionByIdDataLoader sessionById,
                CancellationToken cancellationToken)
            {
                int[] sessionIds = await dbContext.Speakers
                    .Where(s => s.Id == speaker.Id)
                    .Include(s => s.SessionSpeakers)
                    .SelectMany(s => s.SessionSpeakers.Select(t => t.SessionId))
                    .ToArrayAsync();

                return await sessionById.LoadAsync(sessionIds, cancellationToken);
            }
        }
```
throws the error :

> There was no argument with the name `speaker` found on the field `sessions

If the `Speaker` parameter is annotated with `[Parent]` then everything works. I have not verified it but I assume that the SessionResolvers and AttendeeResolvers defined in 4-schema-design.md have the same issue.

The section in the user guide regarding arguments for resolvers is really sketchy. It would be very helpful if the paragraph 

> There are also specific arguments that will be automatically populated by Hot Chocolate when the resolver is executed. These include Dependency injection services, DataLoaders, state, or even context like a parent value.

was elaborated. From what is written I understand that any registered service can be injected but I have no idea what is meant by 
>state, or even context like a parent value

**Comment by davorinjurkovic007** [comment]
Thanks.
That solve my problem

**Comment by jeffvan98** [comment]
It would be helpful to have this change reflected in the [workshop](https://github.com/ChilliCream/graphql-workshop/blob/master/docs/3-understanding-dataLoader.md).
