### ISSUE TITLE
How to use projection in data loader

### ISSUE THREAD

**Issue by singha-rayathong** [ChilliCream/graphql-workshop#91]
How to use projection in data loader

**Comment by LangSensei** [comment]
@singha-rayathong 

Have you found the solution? I also encountered this issue.

**Comment by sabuydee** [comment]
@LangSensei 
Nothing 🥲

**Comment by PascalSenn** [comment]
We have an idea how we can solve this problem. We try to make this possible with the dataloader source generator that will come with 13.x.x

**Comment by jorgeparavicini** [comment]
@PascalSenn any news on this?

**Comment by michaelstaib** [comment]
This one is now implemented
