### ISSUE TITLE
Session 3: Unable to resolve service for type 'DAL.PRdbContext' while attempting to activate 'DAL.Repositories.UserRepository'

### ISSUE THREAD

**Issue by francescoosato** [ChilliCream/graphql-workshop#96]
On my solution, As soon as I apply the logic to allow parallel query, I get the following exception:
`Unable to resolve service for type 'DAL.PRdbContext' while attempting to activate 'DAL.Repositories.UserRepository'`

For more details on my project architecture, please visit the [post ](https://stackoverflow.com/questions/71443048/net-graphql-unable-to-resolve-service-for-type-dal-prdbcontext-while-attemp) I created on Stackoverflow.

**Comment by glen-84** [comment]
I'm closing this issue as outdated, as we have an updated workshop on the `main` branch, for Hot Chocolate 14.
